### PR TITLE
Babelify and minify

### PR DESCRIPTION
**Pull request by pelle**
This uses babelify to create releases that actually work in most browsers without shims.

Shims should not be used when there is a better solution for the majority of browsers.

### CODE REVIEW

**Comment by pelle** [comment]
Hi any progress on this? The browser builds are basically pointless if they don't work in a browser ;-)

**Comment by holgerd77** [comment]
@axic Any reasons not to merge this? I know the builds are pretty outdated, but having babelify would be nice?

**Comment by holgerd77** [comment]
@axic Just tried the ``build.sh`` script (with the super-outdated dependencies), at least this still works. :-) Will see if can bring this a bit up-to-date during the next week (more too an experimental state though during the first stage and not an this-can-be-used one).

**Comment by holgerd77** [comment]
Outdated by the latest updates with the integrated JS build script.

**Pull request closed without merging**
